# This is the configuration file for the exchange server.

[global]
starting_accounts = 10
starting_assets = [
    ["United States Dollar", "UsD"],
    ["Euro", "EUR"],
    ["Japanese Yen", "JPY"],
    ["Swiss Frank", "CHF"],
    ["SK Hynix Inc.", "SKHY"], # 4
    ["Adyen N.V.", "ADYEN.AS"], # 5
    ["NVIDIA Corporation", "NVDA"], # 6
    ["ASML Holding N.V.", "ASML"], # 7
    ["Advanced Micro Devices, Inc.", "AMD"] # 8
]

starting_markets = [
    ["AMD", "USD"],
    ["NVDA", "USD"],
    ["ASML", "EUR"],
    ["SKHY", "USD"],
    ["ADYEN.AS", "EUR"],
    ["EUR", "USD"],
    ["JPY", "USD"],
    ["CHF", "USD"],
    ["CHF", "EUR"],
    ["JPY", "EUR"],
]

[dev]
ws_send_interval_ms = 100

[prod]
ws_send_interval_ms = 250